# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acertijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('respuesta', models.TextField()),
            ],
            options={
                'verbose_name': 'Acertijo',
                'verbose_name_plural': 'Acertijos',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('n_tesoro', models.IntegerField()),
                ('icono', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='../image/')),
            ],
            options={
                'verbose_name': 'Medalla',
                'verbose_name_plural': 'Medallas',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_piel', models.CharField(default='#FFFFFF', max_length=10)),
                ('color_camiseta', models.CharField(default='#FFFFFF', max_length=10)),
                ('color_cabello', models.CharField(default='#FFFFFF', max_length=10)),
                ('sexo', models.CharField(max_length=1)),
                ('ranking', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Tesoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('icono', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='../image/')),
                ('acertijo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Acertijo')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Facultad')),
                ('medalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Medalla')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tesoro',
                'verbose_name_plural': 'Tesoros',
            },
        ),
    ]
