# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(choices=[(b'H', b'Hombre'), (b'M', b'Mujer')], default=b'H', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.User'),
        ),
        migrations.AlterField(
            model_name='tesoro',
            name='user',
            field=models.ManyToManyField(to='proyecto.User'),
        ),
    ]
