# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20170331_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proyecto.Profile'),
        ),
    ]
