# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_facultad_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('acertijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Acertijo')),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
